#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <wincodec.h>
#include <cstdint>
#include <cstdarg>
#include <cstdio>
#include <cstring>
#include <vector>
#include <algorithm>
#include <mutex>

#include "../include/MinHook/include/MinHook.h"

namespace {
constexpr uint32_t ADDR_PRELOAD_KIT_GRAPHICS=0x00967B40, ADDR_INIT_KIT_CONTEXT=0x00966D50, ADDR_KIT_POST=0x009678E0, ADDR_BUILD_KIT_TEXTURE=0x00954B80, ADDR_REGISTER_TEXTURE=0x00953660, TEAM_IDS_ADDR=0x03BE0940, ADDR_SETUP=0x00967EF0;
constexpr uint16_t DONOR_TEAM=6;
constexpr uint32_t CALL_CTX=0x00967F15, CALL_POST=0x00967F3B, CALL_BUILD_VARIANT=0x009671DD;
constexpr uint32_t CALL_SETUP[4]={0x00968051,0x00968073,0x00968091,0x009680AF};
constexpr int KIT_W=512, KIT_H=256;
constexpr uint32_t KIT_BLOB_MIN=0x80+0x400+KIT_W*KIT_H;
HMODULE g_self=nullptr; HANDLE g_log=INVALID_HANDLE_VALUE; std::mutex g_logMutex;
volatile LONG g_activeTeam=-1, g_activeVariant=-1, g_replacedThisBuild=0;
using FN_Preload=uint32_t(__cdecl*)(); using FN_RegisterTexture=uint32_t*(__cdecl*)(uint32_t);
using FN_BuildKitTexture=uint32_t(__cdecl*)(uint32_t,uint32_t,uint32_t,uint32_t,uint32_t);
using FN_KitSetup=void(__cdecl*)(uint32_t,uint32_t,uint32_t,uint32_t); using FN_KitPost=void(__cdecl*)(uint32_t,uint32_t,uint32_t);
FN_Preload g_origPreload=nullptr; FN_RegisterTexture g_origRegisterTexture=nullptr;
const auto g_nativeBuildKitTexture=reinterpret_cast<FN_BuildKitTexture>(ADDR_BUILD_KIT_TEXTURE);
const auto g_nativeKitSetup=reinterpret_cast<FN_KitSetup>(ADDR_SETUP); const auto g_nativeKitPost=reinterpret_cast<FN_KitPost>(ADDR_KIT_POST);
struct RGBA{uint8_t r,g,b,a;};
const wchar_t* VariantName(int v){static const wchar_t* n[4]={L"ga",L"pa",L"gb",L"pb"}; return(v>=0&&v<4)?n[v]:L"";}
void OpenLog(){char p[MAX_PATH]={}; if(!GetModuleFileNameA(g_self,p,MAX_PATH))return; char* s=strrchr(p,'\\'); if(!s)s=strrchr(p,'/'); if(s)*(s+1)=0;else p[0]=0; strncat_s(p,"PESModKits.log",_TRUNCATE); g_log=CreateFileA(p,GENERIC_WRITE,FILE_SHARE_READ|FILE_SHARE_WRITE,nullptr,CREATE_ALWAYS,FILE_ATTRIBUTE_NORMAL,nullptr);}
void Log(const char* f,...){if(g_log==INVALID_HANDLE_VALUE)return; char b[1024]; va_list a;va_start(a,f);_vsnprintf_s(b,sizeof(b),_TRUNCATE,f,a);va_end(a);std::lock_guard<std::mutex>l(g_logMutex);DWORD w=0;WriteFile(g_log,b,(DWORD)strlen(b),&w,nullptr);WriteFile(g_log,"\r\n",2,&w,nullptr);FlushFileBuffers(g_log);}
bool FileExists(const wchar_t* p){DWORD a=GetFileAttributesW(p);return a!=INVALID_FILE_ATTRIBUTES&&!(a&FILE_ATTRIBUTE_DIRECTORY);}
void MakeKitPath(uint16_t t,int v,wchar_t(&p)[MAX_PATH]){_snwprintf_s(p,_TRUNCATE,L".\\kits\\%u\\%s.png",(unsigned)t,VariantName(v));}
bool HasVariantPng(uint16_t t,int v){wchar_t p[MAX_PATH];MakeKitPath(t,v,p);return FileExists(p);} bool HasAnyKitPng(uint16_t t){for(int v=0;v<4;++v)if(HasVariantPng(t,v))return true;return false;}
inline int SwzIndex(int x,int y,int w){int block=(y&~0xf)*w+(x&~0xf)*2,swap=(((y+2)>>2)&1)*4,ypos=(((y&~3)>>1)+(y&1))&7,col=ypos*w*2+((x+swap)&7)*4;return block+col+((y>>1)&1)+((x>>2)&2);}
void ClutSwap(uint8_t* p){for(int b=0;b<256;b+=32)for(int k=0;k<8;++k)for(int c=0;c<4;++c)std::swap(p[(b+8+k)*4+c],p[(b+16+k)*4+c]);}
void MedianCut(const std::vector<RGBA>&px,std::vector<RGBA>&pal,std::vector<uint8_t>&idx){std::vector<std::vector<int>>boxes(1);boxes[0].resize(px.size());for(size_t i=0;i<px.size();++i)boxes[0][i]=(int)i;auto range=[&](const std::vector<int>&box,int&ax){uint8_t mn[4]={255,255,255,255},mx[4]={0,0,0,0};for(int i:box){const uint8_t*v=&px[i].r;for(int c=0;c<4;++c){mn[c]=std::min(mn[c],v[c]);mx[c]=std::max(mx[c],v[c]);}}int best=0;ax=0;for(int c=0;c<4;++c){int r=mx[c]-mn[c];if(r>best){best=r;ax=c;}}return best;};while(boxes.size()<256){int bi=-1,br=-1,ba=0;for(size_t k=0;k<boxes.size();++k){if(boxes[k].size()<2)continue;int a=0,r=range(boxes[k],a);if(r>br){br=r;bi=(int)k;ba=a;}}if(bi<0)break;auto box=std::move(boxes[bi]);boxes.erase(boxes.begin()+bi);std::sort(box.begin(),box.end(),[&](int a,int b){return(&px[a].r)[ba]<(&px[b].r)[ba];});size_t m=box.size()/2;boxes.emplace_back(box.begin(),box.begin()+m);boxes.emplace_back(box.begin()+m,box.end());}pal.assign(256,RGBA{0,0,0,0});idx.assign(px.size(),0);for(size_t k=0;k<boxes.size()&&k<256;++k){auto&box=boxes[k];if(box.empty())continue;uint64_t s[4]={};for(int i:box){s[0]+=px[i].r;s[1]+=px[i].g;s[2]+=px[i].b;s[3]+=px[i].a;}uint64_t n=box.size();pal[k]=RGBA{(uint8_t)(s[0]/n),(uint8_t)(s[1]/n),(uint8_t)(s[2]/n),(uint8_t)(s[3]/n)};for(int i:box)idx[i]=(uint8_t)k;}}
bool DecodeKitPng(const wchar_t*p,std::vector<RGBA>&out){HRESULT init=CoInitializeEx(nullptr,COINIT_MULTITHREADED);bool did=SUCCEEDED(init);IWICImagingFactory*f=nullptr;IWICBitmapDecoder*d=nullptr;IWICBitmapFrameDecode*fr=nullptr;IWICFormatConverter*c=nullptr;bool ok=false;do{if(FAILED(CoCreateInstance(CLSID_WICImagingFactory,nullptr,CLSCTX_INPROC_SERVER,IID_PPV_ARGS(&f))))break;if(FAILED(f->CreateDecoderFromFilename(p,nullptr,GENERIC_READ,WICDecodeMetadataCacheOnDemand,&d)))break;if(FAILED(d->GetFrame(0,&fr)))break;UINT w=0,h=0;if(FAILED(fr->GetSize(&w,&h)))break;if(w!=KIT_W||h!=KIT_H){Log("[CustomKitPNG] rejected PNG: expected 512x256, got %ux%u",w,h);break;}if(FAILED(f->CreateFormatConverter(&c)))break;if(FAILED(c->Initialize(fr,GUID_WICPixelFormat32bppRGBA,WICBitmapDitherTypeNone,nullptr,0.0,WICBitmapPaletteTypeCustom)))break;out.resize((size_t)KIT_W*KIT_H);if(FAILED(c->CopyPixels(nullptr,KIT_W*4,(UINT)out.size()*4,(BYTE*)out.data())))break;ok=true;}while(false);if(c)c->Release();if(fr)fr->Release();if(d)d->Release();if(f)f->Release();if(did)CoUninitialize();return ok;}
bool LooksLikeKitBlob(uint8_t*b){if(!b)return false;__try{uint32_t magic=*(uint32_t*)(b),sz=*(uint32_t*)(b+8),dims=*(uint32_t*)(b+0x14);return magic==0x29857294u&&sz>=KIT_BLOB_MIN&&(dims&0xffff)==KIT_W&&(dims>>16)==KIT_H&&b[0x18]==2&&b[0x19]==0x13;}__except(EXCEPTION_EXECUTE_HANDLER){return false;}}
bool ReplaceBlobFromPng(uint8_t*b,uint16_t t,int v){if(!LooksLikeKitBlob(b)||!HasVariantPng(t,v))return false;wchar_t p[MAX_PATH];MakeKitPath(t,v,p);std::vector<RGBA>rgba;if(!DecodeKitPng(p,rgba)){Log("[CustomKitPNG] team=%u variant=%d decode failed",t,v);return false;}std::vector<RGBA>pal;std::vector<uint8_t>idx;MedianCut(rgba,pal,idx);uint8_t*cl=b+0x80;for(int i=0;i<256;++i){RGBA q=pal[i];int a=(q.a+1)/2;if(a>128)a=128;cl[i*4]=q.r;cl[i*4+1]=q.g;cl[i*4+2]=q.b;cl[i*4+3]=(uint8_t)a;}ClutSwap(cl);uint8_t*pix=b+0x480;memset(pix,0,KIT_W*KIT_H);for(int y=0;y<KIT_H;++y)for(int x=0;x<KIT_W;++x)pix[SwzIndex(x,y,KIT_W)]=idx[y*KIT_W+x];uint32_t id=*(uint32_t*)(b+0x0c);Log("[CustomKitPNG] team=%u variant=%d display=0x%X replaced 512x256",t,v,id);return true;}
bool ValidateCall(uint32_t s,uint32_t e){uint8_t*p=(uint8_t*)s;__try{if(p[0]!=0xE8)return false;int32_t r=*(int32_t*)(p+1);return(uint32_t)(p+5+r)==e;}__except(EXCEPTION_EXECUTE_HANDLER){return false;}}
bool PatchCall(uint32_t s,uint32_t e,void*h){if(!ValidateCall(s,e)){Log("[CustomKitPNG] ERROR callsite 0x%08X mismatch",s);return false;}uint8_t*p=(uint8_t*)s;DWORD o=0;if(!VirtualProtect(p,5,PAGE_EXECUTE_READWRITE,&o))return false;*(int32_t*)(p+1)=(int32_t)((uint8_t*)h-(p+5));DWORD q;VirtualProtect(p,5,o,&q);FlushInstructionCache(GetCurrentProcess(),p,5);return true;}
uint32_t __cdecl HookPreload(){volatile uint16_t*ids=(volatile uint16_t*)TEAM_IDS_ADDR;uint16_t a=ids[0],b=ids[1];bool ca=HasAnyKitPng(a),cb=HasAnyKitPng(b);if(ca)ids[0]=DONOR_TEAM;if(cb)ids[1]=DONOR_TEAM;if(ca||cb)Log("[CustomKitPNG] preload proxy home=%u%s away=%u%s donor=%u",a,ca?"*":"",b,cb?"*":"",DONOR_TEAM);uint32_t r=g_origPreload?g_origPreload():0;ids[0]=a;ids[1]=b;return r;}
extern "C" __declspec(naked) void KitContextProxy(){__asm{mov eax,g_activeTeam cmp eax,-1 je passthrough movzx edx,bx cmp edx,eax jne passthrough push ebx mov bx,6 mov eax,ADDR_INIT_KIT_CONTEXT call eax pop ebx ret passthrough: mov eax,ADDR_INIT_KIT_CONTEXT call eax ret}}
void __cdecl KitPostProxy(uint32_t t,uint32_t a2,uint32_t a3){if(g_activeTeam>=0&&t==(uint32_t)g_activeTeam)g_nativeKitPost(DONOR_TEAM,a2,a3);else g_nativeKitPost(t,a2,a3);}
uint32_t __cdecl BuildVariantProxy(uint32_t tok,uint32_t a2,uint32_t a3,uint32_t a4,uint32_t a5){LONG pv=g_activeVariant,pd=g_replacedThisBuild;if(g_activeTeam>=0&&tok>=0x733e&&tok<=0x7341){g_activeVariant=(LONG)(tok-0x733e);g_replacedThisBuild=0;}uint32_t r=g_nativeBuildKitTexture(tok,a2,a3,a4,a5);g_activeVariant=pv;g_replacedThisBuild=pd;return r;}
void __cdecl KitSetupProxy(uint32_t t,uint32_t a2,uint32_t a3,uint32_t a4){LONG pt=g_activeTeam;if(t<=0xffff&&HasAnyKitPng((uint16_t)t)){g_activeTeam=(LONG)t;Log("[CustomKitPNG] setup team=%u using donor=%u",t,DONOR_TEAM);}g_nativeKitSetup(t,a2,a3,a4);g_activeTeam=pt;}
uint32_t* __cdecl HookRegisterTexture(uint32_t bv){uint8_t*b=(uint8_t*)bv;LONG t=g_activeTeam,v=g_activeVariant;if(t>=0&&t<=0xffff&&v>=0&&v<4&&InterlockedCompareExchange(&g_replacedThisBuild,1,0)==0){if(!ReplaceBlobFromPng(b,(uint16_t)t,(int)v))InterlockedExchange(&g_replacedThisBuild,0);}return g_origRegisterTexture?g_origRegisterTexture(bv):nullptr;}
bool Install(){for(uint32_t s:CALL_SETUP)if(!ValidateCall(s,ADDR_SETUP)){Log("[CustomKitPNG] ERROR setup call 0x%08X validation",s);return false;}if(!ValidateCall(CALL_CTX,ADDR_INIT_KIT_CONTEXT)||!ValidateCall(CALL_POST,ADDR_KIT_POST)||!ValidateCall(CALL_BUILD_VARIANT,ADDR_BUILD_KIT_TEXTURE)){Log("[CustomKitPNG] ERROR internal callsite validation; untouched");return false;}MH_STATUS st=MH_Initialize();if(st!=MH_OK&&st!=MH_ERROR_ALREADY_INITIALIZED){Log("[CustomKitPNG] ERROR MH init=%d",st);return false;}st=MH_CreateHook((void*)ADDR_PRELOAD_KIT_GRAPHICS,(void*)&HookPreload,(void**)&g_origPreload);if(st!=MH_OK&&st!=MH_ERROR_ALREADY_CREATED){Log("[CustomKitPNG] ERROR preload create=%d",st);return false;}st=MH_EnableHook((void*)ADDR_PRELOAD_KIT_GRAPHICS);if(st!=MH_OK&&st!=MH_ERROR_ENABLED){Log("[CustomKitPNG] ERROR preload enable=%d",st);return false;}st=MH_CreateHook((void*)ADDR_REGISTER_TEXTURE,(void*)&HookRegisterTexture,(void**)&g_origRegisterTexture);if(st!=MH_OK&&st!=MH_ERROR_ALREADY_CREATED){Log("[CustomKitPNG] ERROR texture create=%d",st);return false;}st=MH_EnableHook((void*)ADDR_REGISTER_TEXTURE);if(st!=MH_OK&&st!=MH_ERROR_ENABLED){Log("[CustomKitPNG] ERROR texture enable=%d",st);return false;}if(!PatchCall(CALL_CTX,ADDR_INIT_KIT_CONTEXT,(void*)&KitContextProxy)||!PatchCall(CALL_POST,ADDR_KIT_POST,(void*)&KitPostProxy)||!PatchCall(CALL_BUILD_VARIANT,ADDR_BUILD_KIT_TEXTURE,(void*)&BuildVariantProxy))return false;for(uint32_t s:CALL_SETUP)if(!PatchCall(s,ADDR_SETUP,(void*)&KitSetupProxy))return false;Log("[CustomKitPNG] installed. PESMod.asi untouched.");return true;}
DWORD WINAPI Worker(void*){OpenLog();Log("PESModKits v0.1 starting");bool ready=false;for(int i=0;i<600;++i){HMODULE m=GetModuleHandleA("PESMod.asi");if(!m)m=GetModuleHandleA("PESMod(7).asi");__try{if(m&&*(volatile uint8_t*)0x00865240==0xE9){ready=true;break;}}__except(EXCEPTION_EXECUTE_HANDLER){}Sleep(100);}if(!ready){Log("[CustomKitPNG] ERROR PESMod hook not detected; game untouched");return 0;}Install();return 0;}
}
BOOL APIENTRY DllMain(HMODULE h,DWORD r,LPVOID){if(r==DLL_PROCESS_ATTACH){g_self=h;DisableThreadLibraryCalls(h);HANDLE t=CreateThread(nullptr,0,Worker,nullptr,0,nullptr);if(t)CloseHandle(t);}else if(r==DLL_PROCESS_DETACH&&g_log!=INVALID_HANDLE_VALUE){CloseHandle(g_log);g_log=INVALID_HANDLE_VALUE;}return TRUE;}
